// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DiscoVotefinder {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class PostTemplate : PostTemplateBase {
        
        private int _DayField;
        public int Day {
            get {
                return this._DayField;
            }
        }
        private System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player> _PlayersField;
        public System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player> Players {
            get {
                return this._PlayersField;
            }
        }
        private string _MotdField;
        public string Motd {
            get {
                return this._MotdField;
            }
        }
        private System.DateTime _DeadlineField;
        public System.DateTime Deadline {
            get {
                return this._DeadlineField;
            }
        }
        private int _TopicField;
        public int Topic {
            get {
                return this._TopicField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 11 ""
 
var Targets = Players.Where(p => p.VotesAgainst.Count > 0).OrderByDescending(p => p.Votecount).ThenBy(p => p.Name);
var NotVoting = Players.Where(p => p.CurrentVote == null).OrderBy(p => p.Name);
var Laggards = Players.Where(p => (DateTime.UtcNow - p.LastPost).TotalDays > 1).OrderBy(p => p.LastPost).ThenBy(p => p.Name);
var PlayerCount = Players.Count();
var Until = Deadline - DateTime.Now;
 
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("<u>Votecount for Day ");
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Day ));
            
            #line default
            #line hidden
            
            #line 18 ""
            this.Write("</u>\n<table>\n");
            
            #line default
            #line hidden
            
            #line 20 ""
 foreach(var p in Targets) { 
            
            #line default
            #line hidden
            
            #line 21 ""
            this.Write("<tr>\n<td><img src=\"");
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( SvgGenerator.GenerateDataUri(PlayerCount, p.Votecount) ));
            
            #line default
            #line hidden
            
            #line 22 ""
            this.Write("\" width=\"100\" height=\"12\"/></td>\n<td><b>");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( p.Name ));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(" (");
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( p.Votecount ));
            
            #line default
            #line hidden
            
            #line 23 ""
            this.Write("):</b></td>\n<td>");
            
            #line default
            #line hidden
            
            #line 24 ""

foreach(var v in p.VotesAgainst) {
if(v.UnvotePostNum == 0) Write("<b>"); 

            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write("<a href=\"/t/");
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Topic ));
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write("/");
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(v.VotePostNum));
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write("\">");
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(v.Actor));
            
            #line default
            #line hidden
            
            #line 28 ""
            this.Write("</a>");
            
            #line default
            #line hidden
            
            #line 28 ""
if(v.UnvotePostNum != 0) { 
	
            
            #line default
            #line hidden
            
            #line 30 ""
            this.Write(" <a href=\"/t/");
            
            #line default
            #line hidden
            
            #line 30 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Topic ));
            
            #line default
            #line hidden
            
            #line 30 ""
            this.Write("/");
            
            #line default
            #line hidden
            
            #line 30 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(v.UnvotePostNum));
            
            #line default
            #line hidden
            
            #line 30 ""
            this.Write("\">[X]</a>");
            
            #line default
            #line hidden
            
            #line 30 ""

	} else Write("</b>"); 
            
            #line default
            #line hidden
            
            #line 32 ""
            this.Write(", \n");
            
            #line default
            #line hidden
            
            #line 33 ""
}
            
            #line default
            #line hidden
            
            #line 34 ""
            this.Write("</td>\n</tr>\n");
            
            #line default
            #line hidden
            
            #line 36 ""
 } 
            
            #line default
            #line hidden
            
            #line 37 ""
            this.Write("<tr>\n<td><img src=\"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7\" width=\"100\" height=\"12\"/></td>\n<td><b>Not Voting (");
            
            #line default
            #line hidden
            
            #line 39 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( NotVoting.Count() ));
            
            #line default
            #line hidden
            
            #line 39 ""
            this.Write("):</b></td>\n<td>");
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( String.Join(", ", NotVoting.Select(nv => nv.Name)) ));
            
            #line default
            #line hidden
            
            #line 40 ""
            this.Write("\n</td>\n</tr>\n</table>\n");
            
            #line default
            #line hidden
            
            #line 44 ""
if(!String.IsNullOrWhiteSpace(Motd)) {
            
            #line default
            #line hidden
            
            #line 45 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Motd ));
            
            #line default
            #line hidden
            
            #line 46 ""
            this.Write("\n");
            
            #line default
            #line hidden
            
            #line 47 ""
}
            
            #line default
            #line hidden
            
            #line 48 ""
            this.Write("\nWith ");
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( PlayerCount ));
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(" players, it's **");
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( Math.Ceiling(PlayerCount / 2.0).ToString("0") ));
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(" to execute!** Deadline is on ");
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Deadline.ToString("D")));
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(" at ");
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Deadline.ToString("t")));
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 49 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(
TimeZoneInfo.Local.IsDaylightSavingTime(Deadline) ? TimeZoneInfo.Local.DaylightName : TimeZoneInfo.Local.StandardName ));
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(" &mdash; that's in **");
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Until.Days * 24 + Until.Hours));
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(" hours, ");
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(this.ToStringHelper.ToStringWithCulture(Until.Minutes));
            
            #line default
            #line hidden
            
            #line 50 ""
            this.Write(" minutes!**\n");
            
            #line default
            #line hidden
            
            #line 51 ""
if(Laggards.Count() > 0) { 
            
            #line default
            #line hidden
            
            #line 52 ""
            this.Write("\n:warning: These players have not posted in 24 hours or more!\n");
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write(this.ToStringHelper.ToStringWithCulture( String.Join(", ", Laggards.Select(l => "@" + l.Name)) ));
            
            #line default
            #line hidden
            
            #line 54 ""
            this.Write("\n\nPlayers must post at least once every 24 hours or risk elimination!\n");
            
            #line default
            #line hidden
            
            #line 57 ""
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                bool _DayAcquired = false;
                if (((this.Session != null) && this.Session.ContainsKey("Day"))) {
                    object data = this.Session["Day"];
                    if (typeof(int).IsAssignableFrom(data.GetType())) {
                        this._DayField = ((int)(data));
                        _DayAcquired = true;
                    }
                    else {
                        this.Error("The type 'System.Int32' of the parameter 'Day' did not match the type passed to the template");
                    }
                }
                if ((_DayAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Day");
                    if ((data != null)) {
                        if (typeof(int).IsAssignableFrom(data.GetType())) {
                            this._DayField = ((int)(data));
                            _DayAcquired = true;
                        }
                        else {
                            this.Error("The type 'System.Int32' of the parameter 'Day' did not match the type passed to the template");
                        }
                    }
                }
                bool _PlayersAcquired = false;
                if (((this.Session != null) && this.Session.ContainsKey("Players"))) {
                    object data = this.Session["Players"];
                    if (typeof(System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>).IsAssignableFrom(data.GetType())) {
                        this._PlayersField = ((System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>)(data));
                        _PlayersAcquired = true;
                    }
                    else {
                        this.Error("The type 'System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>' of the parameter 'Players' did not match the type passed to the template");
                    }
                }
                if ((_PlayersAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Players");
                    if ((data != null)) {
                        if (typeof(System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>).IsAssignableFrom(data.GetType())) {
                            this._PlayersField = ((System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>)(data));
                            _PlayersAcquired = true;
                        }
                        else {
                            this.Error("The type 'System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>' of the parameter 'Players' did not match the type passed to the template");
                        }
                    }
                }
                bool _MotdAcquired = false;
                if (((this.Session != null) && this.Session.ContainsKey("Motd"))) {
                    object data = this.Session["Motd"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._MotdField = ((string)(data));
                        _MotdAcquired = true;
                    }
                    else {
                        this.Error("The type 'System.String' of the parameter 'Motd' did not match the type passed to the template");
                    }
                }
                if ((_MotdAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Motd");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._MotdField = ((string)(data));
                            _MotdAcquired = true;
                        }
                        else {
                            this.Error("The type 'System.String' of the parameter 'Motd' did not match the type passed to the template");
                        }
                    }
                }
                bool _DeadlineAcquired = false;
                if (((this.Session != null) && this.Session.ContainsKey("Deadline"))) {
                    object data = this.Session["Deadline"];
                    if (typeof(System.DateTime).IsAssignableFrom(data.GetType())) {
                        this._DeadlineField = ((System.DateTime)(data));
                        _DeadlineAcquired = true;
                    }
                    else {
                        this.Error("The type 'System.DateTime' of the parameter 'Deadline' did not match the type passed to the template");
                    }
                }
                if ((_DeadlineAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Deadline");
                    if ((data != null)) {
                        if (typeof(System.DateTime).IsAssignableFrom(data.GetType())) {
                            this._DeadlineField = ((System.DateTime)(data));
                            _DeadlineAcquired = true;
                        }
                        else {
                            this.Error("The type 'System.DateTime' of the parameter 'Deadline' did not match the type passed to the template");
                        }
                    }
                }
                bool _TopicAcquired = false;
                if (((this.Session != null) && this.Session.ContainsKey("Topic"))) {
                    object data = this.Session["Topic"];
                    if (typeof(int).IsAssignableFrom(data.GetType())) {
                        this._TopicField = ((int)(data));
                        _TopicAcquired = true;
                    }
                    else {
                        this.Error("The type 'System.Int32' of the parameter 'Topic' did not match the type passed to the template");
                    }
                }
                if ((_TopicAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Topic");
                    if ((data != null)) {
                        if (typeof(int).IsAssignableFrom(data.GetType())) {
                            this._TopicField = ((int)(data));
                            _TopicAcquired = true;
                        }
                        else {
                            this.Error("The type 'System.Int32' of the parameter 'Topic' did not match the type passed to the template");
                        }
                    }
                }
            }

        }
    }
    
    public class PostTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
