// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DiscoVotefinder
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class PostTemplate : PostTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 11 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
 
var Targets = Players.Where(p => p.VotesAgainst.Count > 0).OrderByDescending(p => p.Votecount).ThenBy(p => p.VotesAgainst.Last().VotePostNum);
var NotVoting = Players.Where(p => p.CurrentVote == null).OrderBy(p => p.Name);
var Laggards = Players.Where(p => (DateTime.UtcNow - p.LastPost).TotalDays > 1).OrderBy(p => p.LastPost).ThenBy(p => p.Name);
var PlayerCount = Players.Count();
var Until = Deadline - DateTime.Now;
 
            
            #line default
            #line hidden
            this.Write("<u>Votecount for Day ");
            
            #line 18 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Day));
            
            #line default
            #line hidden
            this.Write("</u>\r\n<table>\r\n");
            
            #line 20 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
 foreach(var p in Targets) { 
            
            #line default
            #line hidden
            this.Write("<tr>\r\n<td><img src=\"");
            
            #line 22 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SvgGenerator.GenerateDataUri(PlayerCount, p.Votecount)));
            
            #line default
            #line hidden
            this.Write("\" width=\"100\" height=\"12\"/></td>\r\n<td><b>");
            
            #line 23 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Name));
            
            #line default
            #line hidden
            this.Write(" (");
            
            #line 23 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(p.Votecount));
            
            #line default
            #line hidden
            this.Write("):</b></td>\r\n<td>");
            
            #line 24 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"

foreach(var v in p.VotesAgainst) {
if(v.UnvotePostNum == 0) Write("<b>"); 

            
            #line default
            #line hidden
            this.Write("<a href=\"/t/");
            
            #line 27 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Topic));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 27 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(v.VotePostNum));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 27 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(v.Actor));
            
            #line default
            #line hidden
            this.Write("</a>");
            
            #line 27 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
if(v.UnvotePostNum != 0) { 
	
            
            #line default
            #line hidden
            this.Write(" <a href=\"/t/");
            
            #line 28 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Topic));
            
            #line default
            #line hidden
            this.Write("/");
            
            #line 28 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(v.UnvotePostNum));
            
            #line default
            #line hidden
            this.Write("\">[X]</a>");
            
            #line 28 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"

	} else Write("</b>"); 
            
            #line default
            #line hidden
            this.Write(", \r\n");
            
            #line 30 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("</td>\r\n</tr>\r\n");
            
            #line 32 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("<tr>\r\n<td><img src=\"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAA" +
                    "AAAABAAEAAAIBRAA7\" width=\"100\" height=\"12\"/></td>\r\n<td><b>Not Voting (");
            
            #line 35 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NotVoting.Count()));
            
            #line default
            #line hidden
            this.Write("):</b></td>\r\n<td>");
            
            #line 36 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", NotVoting.Select(nv => nv.Name))));
            
            #line default
            #line hidden
            this.Write("\r\n</td>\r\n</tr>\r\n</table>\r\n");
            
            #line 40 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
if(!String.IsNullOrWhiteSpace(Motd)) {
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 42 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Motd));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\nWith ");
            
            #line 45 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PlayerCount));
            
            #line default
            #line hidden
            this.Write(" players, it\'s **");
            
            #line 45 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Ceiling((PlayerCount + 0.5) / 2.0).ToString("0")));
            
            #line default
            #line hidden
            this.Write(" to execute!** Deadline is on [");
            
            #line 45 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Deadline.ToString("D")));
            
            #line default
            #line hidden
            this.Write(" at ");
            
            #line 45 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Deadline.ToString("t")));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 45 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TimeZoneInfo.Local.IsDaylightSavingTime(Deadline) ? TimeZoneInfo.Local.DaylightName : TimeZoneInfo.Local.StandardName));
            
            #line default
            #line hidden
            this.Write("](http://currentmillis.com/?");
            
            #line 46 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((Deadline.ToUniversalTime() - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds.ToString("0")));
            
            #line default
            #line hidden
            this.Write(") &mdash; that\'s in **");
            
            #line 47 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Until.Days * 24 + Until.Hours));
            
            #line default
            #line hidden
            this.Write(" hours, ");
            
            #line 47 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Until.Minutes));
            
            #line default
            #line hidden
            this.Write(" minutes!**\r\n");
            
            #line 48 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
if(Laggards.Count() > 0) { 
            
            #line default
            #line hidden
            this.Write("\r\n:warning: These players have not posted in 24 hours or more!\r\n");
            
            #line 51 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(", ", Laggards.Select(l => "@" + l.Name))));
            
            #line default
            #line hidden
            this.Write("\r\n\r\nPlayers must post at least once every 24 hours or risk elimination!\r\n");
            
            #line 54 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\dev_07\Documents\GitHub\DiscoVotefinder\PostTemplate.tt"

private int _DayField;

/// <summary>
/// Access the Day parameter of the template.
/// </summary>
private int Day
{
    get
    {
        return this._DayField;
    }
}

private global::System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player> _PlayersField;

/// <summary>
/// Access the Players parameter of the template.
/// </summary>
private global::System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player> Players
{
    get
    {
        return this._PlayersField;
    }
}

private string _MotdField;

/// <summary>
/// Access the Motd parameter of the template.
/// </summary>
private string Motd
{
    get
    {
        return this._MotdField;
    }
}

private global::System.DateTime _DeadlineField;

/// <summary>
/// Access the Deadline parameter of the template.
/// </summary>
private global::System.DateTime Deadline
{
    get
    {
        return this._DeadlineField;
    }
}

private int _TopicField;

/// <summary>
/// Access the Topic parameter of the template.
/// </summary>
private int Topic
{
    get
    {
        return this._TopicField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool DayValueAcquired = false;
if (this.Session.ContainsKey("Day"))
{
    if ((typeof(int).IsAssignableFrom(this.Session["Day"].GetType()) == false))
    {
        this.Error("The type \'System.Int32\' of the parameter \'Day\' did not match the type of the data" +
                " passed to the template.");
    }
    else
    {
        this._DayField = ((int)(this.Session["Day"]));
        DayValueAcquired = true;
    }
}
if ((DayValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Day");
    if ((data != null))
    {
        if ((typeof(int).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.Int32\' of the parameter \'Day\' did not match the type of the data" +
                    " passed to the template.");
        }
        else
        {
            this._DayField = ((int)(data));
        }
    }
}
bool PlayersValueAcquired = false;
if (this.Session.ContainsKey("Players"))
{
    if ((typeof(global::System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>).IsAssignableFrom(this.Session["Players"].GetType()) == false))
    {
        this.Error("The type \'System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player" +
                ">\' of the parameter \'Players\' did not match the type of the data passed to the t" +
                "emplate.");
    }
    else
    {
        this._PlayersField = ((global::System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>)(this.Session["Players"]));
        PlayersValueAcquired = true;
    }
}
if ((PlayersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Players");
    if ((data != null))
    {
        if ((typeof(global::System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player" +
                    ">\' of the parameter \'Players\' did not match the type of the data passed to the t" +
                    "emplate.");
        }
        else
        {
            this._PlayersField = ((global::System.Collections.Generic.IEnumerable<DiscoVotefinder.MainClass.Player>)(data));
        }
    }
}
bool MotdValueAcquired = false;
if (this.Session.ContainsKey("Motd"))
{
    if ((typeof(string).IsAssignableFrom(this.Session["Motd"].GetType()) == false))
    {
        this.Error("The type \'System.String\' of the parameter \'Motd\' did not match the type of the da" +
                "ta passed to the template.");
    }
    else
    {
        this._MotdField = ((string)(this.Session["Motd"]));
        MotdValueAcquired = true;
    }
}
if ((MotdValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Motd");
    if ((data != null))
    {
        if ((typeof(string).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.String\' of the parameter \'Motd\' did not match the type of the da" +
                    "ta passed to the template.");
        }
        else
        {
            this._MotdField = ((string)(data));
        }
    }
}
bool DeadlineValueAcquired = false;
if (this.Session.ContainsKey("Deadline"))
{
    if ((typeof(global::System.DateTime).IsAssignableFrom(this.Session["Deadline"].GetType()) == false))
    {
        this.Error("The type \'System.DateTime\' of the parameter \'Deadline\' did not match the type of " +
                "the data passed to the template.");
    }
    else
    {
        this._DeadlineField = ((global::System.DateTime)(this.Session["Deadline"]));
        DeadlineValueAcquired = true;
    }
}
if ((DeadlineValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Deadline");
    if ((data != null))
    {
        if ((typeof(global::System.DateTime).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.DateTime\' of the parameter \'Deadline\' did not match the type of " +
                    "the data passed to the template.");
        }
        else
        {
            this._DeadlineField = ((global::System.DateTime)(data));
        }
    }
}
bool TopicValueAcquired = false;
if (this.Session.ContainsKey("Topic"))
{
    if ((typeof(int).IsAssignableFrom(this.Session["Topic"].GetType()) == false))
    {
        this.Error("The type \'System.Int32\' of the parameter \'Topic\' did not match the type of the da" +
                "ta passed to the template.");
    }
    else
    {
        this._TopicField = ((int)(this.Session["Topic"]));
        TopicValueAcquired = true;
    }
}
if ((TopicValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Topic");
    if ((data != null))
    {
        if ((typeof(int).IsAssignableFrom(data.GetType()) == false))
        {
            this.Error("The type \'System.Int32\' of the parameter \'Topic\' did not match the type of the da" +
                    "ta passed to the template.");
        }
        else
        {
            this._TopicField = ((int)(data));
        }
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class PostTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
